const skills = [{
    image: "html5.png",
    alt: "html5-logo",
    title: "html5"
  }, {
    image: "css3.png",
    alt: "css3-logo",
    title: "css3"
  }, {
    image: "js.png",
    alt: "js-logo",
    title: "javascript"
  }, {
    image: "ts-logo.png",
    alt: "ts-logo",
    title: "typescript"
  }, {
    image: "mongodb-logo.png",
    alt: "mongodb-logo",
    title: "mongodb"
  }, {
    image: "express-logo.png",
    alt: "express-logo",
    title: "express"
  }, {
    image: "react-logo.png",
    alt: "react-logo",
    title: "react"
  }, {
    image: "node-js-logo.png",
    alt: "node-js-logo",
    title: "node js"
  }, {
    image: "angular-logo.png",
    alt: "angular-logo",
    title: "angular js"
  }, {
    image: "tailwind-logo.png",
    alt: "tailwind-logo",
    title: "tailwind css"
  }, {
    image: "bootstrap-logo.png",
    alt: "bootstrap-logo",
    title: "bootstrap"
  }, {
    image: "python-logo.png",
    alt: "python-logo",
    title: "python"
  }, {
    image: "fastapi-logo.svg",
    alt: "fastapi-logo",
    title: "fastapi"
  }, {
    image: "mysql-logo.png",
    alt: "mysql-logo",
    title: "mysql"
  }, {
    image: "postgres-logo.png",
    alt: "postgres-logo",
    title: "postgres"
  }, {
    image: "firebase-logo.png",
    alt: "firebase-logo",
    title: "firebase"
  }, {
    image: "git-logo.png",
    alt: "git-logo",
    title: "git"
  }, {
    image: "github-logo.png",
    alt: "github-logo",
    title: "github"
  }, {
    image: "insomnia-logo.png",
    alt: "insomnia-logo",
    title: "insomnia"
}]

export default skills;